// actionTypes.js
export const GET_RECIPES = 'GET_RECIPES';
export const GET_DIETS = 'GET_DIETS';
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const GET_RECIPES_BY_NAME = "GET_RECIPES_BY_NAME"
export const SEARCH_RECIPES = "SEARCH_RECIPES"
export const SET_SELECTED_RECIPE = 'SET_SELECTED_RECIPE';
// export const SET_DIET_FILTER = 'SET_DIET_FILTER';
// export const SET_ORIGIN_FILTER = 'SET_ORIGIN_FILTER';
// export const SET_SORT_OPTION = 'SET_SORT_OPTION';